import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Rent Car Nasi',
  description: 'Generated by nextJS app',
}

const Home = () => {
  return <div>Rent Car Nasi</div>;
};

export default Home;
